# Site settings
title: Andy & Lyndsay
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mrandmrsyoung2017.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
